#!/usr/bin/env bash
# configure it to our needs so that you can connect to a server without typing a password. 
Host myserver
    HostName myserver.com
    User myuser
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
